#+title: Config

* Just copy the default
$DOOMDIR/config.el -*- lexical-binding: t; -*-
Place your private configuration here! Remember, you do not need to run 'doom sync' after modifying this file!

** Identifier
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets. It is optional.
#+begin_src emacs-lisp
(setq user-full-name "Keara Coara"
      user-mail-address "for156th@gmail.com")
#+end_src

** Appearance
*** Font
Doom exposes five (optional) variables for controlling fonts in Doom:
- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.
- `doom-unicode-font' -- for unicode glyphs
- `doom-serif-font' -- for the `fixed-pitch-serif' face
See 'C-h v doom-font' for documentation and more examples of what they accept.
If you or Emacs can't find your font, use 'M-x describe-font' to look them up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to refresh your font settings. If Emacs still can't find your font, it likely wasn't installed correctly. Font issues are rarely Doom issues!
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Fira Code" :size 20 :weight 'semi-light))
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
#+end_src
*** Theme

There are two ways to load a theme. Both assume the theme is installed and available. You can either set `doom-theme' or manually load a theme with the `load-theme' function. This is the default:
#+begin_src emacs-lisp
(setq doom-theme 'doom-one)
#+end_src

*** Line numbers
This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src
*** Package-config-tips
 Whenever you reconfigure a package, make sure to wrap your config in an ~after!~ block, otherwise Doom's defaults may override your settings. E.g.
#+begin_src emacs-lisp
;   (after! PACKAGE
;     (setq x y))
#+end_src
 The exceptions to this rule:

 - Setting file/directory variables (like ~org-directory~)
 - Setting variables which explicitly tell you to set them before their package is loaded (see 'C-h v VARIABLE' to look up their documentation).
 - Setting doom variables (which start with 'doom-' or '+').

 Here are some additional functions/macros that will help you configure Doom.

 - ~load!~ for loading external *.el files relative to this one
 - ~use-package!~ for configuring packages
 - ~after!~ for running code after a package has loaded
 - ~add-load-path!~ for adding directories to the ~load-path~, relative to this file. Emacs searches the ~load-path~ when you load packages with ~require~ or ~use-package~.
 - ~map!~ for binding new keys

 To get information about any of these functions/macros, move the cursor over the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
 This will open documentation for it, including demos of how they are used.
 Alternatively, use `C-h o' to look up a symbol (functions, variables, faces, etc).

 You can also try 'gd' (or 'C-c c d') to jump to their definition and see how they are implemented.

* Evil
** Evil:Keybindings
#+begin_src emacs-lisp
(evil-global-set-key 'normal (kbd "u") 'evil-previous-line)
(evil-global-set-key 'normal (kbd ",.")'evil-jump-item)
(evil-global-set-key 'normal (kbd "e") 'evil-next-line)
(evil-global-set-key 'normal (kbd "n") 'evil-backward-char)
(evil-global-set-key 'normal (kbd "i") 'evil-forward-char)
(evil-global-set-key 'visual (kbd "u") 'evil-previous-line)
(evil-global-set-key 'visual (kbd "e") 'evil-next-line)
(evil-global-set-key 'visual (kbd "n") 'evil-backward-char)
(evil-global-set-key 'visual (kbd "i") 'evil-forward-char)
(evil-global-set-key 'normal (kbd "N") 'evil-beginning-of-line)
(evil-global-set-key 'normal (kbd "I") 'evil-end-of-line)
(evil-global-set-key 'visual (kbd "N") 'evil-beginning-of-line)
(evil-global-set-key 'visual (kbd "I") 'evil-end-of-line)
(evil-global-set-key 'normal (kbd "h") 'evil-undo)
(evil-global-set-key 'normal (kbd "s") 'evil-insert)
(evil-global-set-key 'normal (kbd "L") 'evil-insert-line)
(evil-global-set-key 'normal (kbd "`") 'evil-invert-char)
(evil-global-set-key 'normal (kbd "S") 'save-buffer)
(evil-global-set-key 'normal (kbd "Q") 'evil-quit)
(evil-global-set-key 'normal (kbd ";") 'evil-ex)
(evil-global-set-key 'normal (kbd "j") 'evil-forward-word-end)
(evil-global-set-key 'normal (kbd "J") 'evil-forward-word-end)
(evil-global-set-key 'normal (kbd "k") (if (eq evil-search-module 'evil-search) 'evil-ex-search-next 'evil-search-next))
(evil-global-set-key 'normal (kbd "K") (if (eq evil-search-module 'evil-search) 'evil-ex-search-previous 'evil-search-previous))
(evil-global-set-key 'normal (kbd "SPC w u") 'evil-window-up)
(evil-global-set-key 'normal (kbd "SPC w e") 'evil-window-down)
(evil-global-set-key 'normal (kbd "SPC w n") 'evil-window-left)
(evil-global-set-key 'normal (kbd "SPC w i") 'evil-window-right)
#+end_src
* Org mode
** Directory
If you use `org' and don't want your org files in the default location below, change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp
(setq org-directory "~/Data/Org/")
#+end_src
** Literal Programming
What babel do you want in source code?
#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((C . t)
   (scheme . t)  ;; I use only geiser-guile
   (python . t)
   (shell . t)))
(setq org-format-latex-options (plist-put org-format-latex-options :scale 3.0))
#+end_src
** Org-agenda
#+begin_src emacs-lisp
(after! org
  (setq org-agenda-files
        '("~/Data/Org/agenda.org")))
(setq org-agenda-time-grid (quote (((daily today require-timed)
                                    (800 1000 1200 1400 1600 1800 2000)
                                    "......" "----------------"))))
(setq org-agenda-include-diary t)
(setq org-agenda-diary-file "~/Data/Org/Diary")
#+end_src
* Chinese

** Pyim
#+begin_src emacs-lisp

(pyim-basedict-enable)
(setq default-input-method "pyim")
(pyim-default-scheme 'microsoft-shuangpin)
(setq pyim-cloudim 'google)
(setq pyim-page-length 8)
(defun my-converter (string)
  (if (equal string "×")
      "*"
    string))
(setq pyim-outcome-magic-converter #'my-converter)
#+end_src
