#!/bin/bash
#     ____  ____  ____  __  ___
#    / __ \/ __ \/ __ \/  |/  /
#   / / / / / / / / / / /|_/ / 
#  / /_/ / /_/ / /_/ / /  / /  
# /_____/\____/\____/_/  /_/   
                             
#     ______                         
#    / ____/___ ___  ____ ___________
#   / __/ / __ `__ \/ __ `/ ___/ ___/
#  / /___/ / / / / / /_/ / /__(__  ) 
# /_____/_/ /_/ /_/\__,_/\___/____/  
                                   
#    _____      __            
#   / ___/___  / /___  ______ 
#   \__ \/ _ \/ __/ / / / __ \
#  ___/ /  __/ /_/ /_/ / /_/ /
# /____/\___/\__/\__,_/ .___/ 
#                    /_/

echo "Doom Emacs 个人配置."
echo "使用linux环境，非常简单！"
echo "使用Windows,个人喜欢用WSL下载Emacs,非常舒适."
echo "MacOS很相似，在此不论。本工具假定你用的是Linux环境."
echo "Waiting..."
sleep 3s

echo "依赖："
echo "Emacs 27.1+"
echo "ripgrep 11.0+"
echo "Git 2.23+"
sleep 1s

git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
~/.emacs.d/bin/doom install
PATH="$HOME/.emacs.d/bin:$PATH"
sleep 5s

~/.emacs.d/bin/doom sync

echo "安装完成！"